import type { Metadata } from "next";
import "./globals.css";
import Providers from "./providers";
import { ThemeProvider } from "@/context/ThemeContext";
import { SidebarProvider } from "@/context/SidebarContext";
import { JetBrains_Mono } from "next/font/google";

const jetbrainsMono = JetBrains_Mono({
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "The 404",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			{/* <body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			> */}
			<body className={`${jetbrainsMono.className} dark:bg-gray-900`}>
				<Providers>
					{" "}
					<ThemeProvider>
						<SidebarProvider>{children}</SidebarProvider>
					</ThemeProvider>
				</Providers>
			</body>
		</html>
	);
}
